### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by ghost** [MaximRouiller/MaximeRouiller.Azure.AppService.EasyAuth#1]
First up, a lovely library. 

There seems to be a bunch of dead code and unused classes - perhaps you intended them as extension points for a future rev? or features that you started on, but didn't make?

Examples are:
EasyAuthProviders.cs
ZumoResponse.cs

Also, it is unclear how EasyAuthAuthenticationOptions is being used.

**Comment by Jeremywhiteley** [comment]
Will this work with easyauth in dot net 3?

**Comment by ghost** [comment]
I don't see any reason why it should not. Do you? I mean, there is nothing "un-core3" in that.
