### ISSUE TITLE
[Authorize(AuthenticationSchemes = "EasyAuth")] - Scheme is not really required

### ISSUE THREAD

**Issue by ghost** [MaximRouiller/MaximeRouiller.Azure.AppService.EasyAuth#2]
Mentioning the scheme name in the attribute is not really required. One can simply decorate the controller (or specific actions within) using just `[Authorize]` and it works perfectly (when not using your library). So why the need to add the property value?

**Comment by dasiths** [comment]
This is correct. It used the default scheme when the Authorize Filter is present. Look how I've done it here https://github.com/dasiths/NEasyAuthMiddleware
