### ISSUE TITLE
Licence is missing

### ISSUE THREAD

**Issue by ie-zero** [MaximRouiller/MaximeRouiller.Azure.AppService.EasyAuth#6]
Thank you very much for providing the code @MaximRouiller 

I noticed though that there is no licence on the code repository, which makes it hard to be used in any meaningful way. Would it be possible to add licence information on the repository please?

**Comment by MaximRouiller** [comment]
Fixed.

**Comment by ie-zero** [comment]
Thank you @MaximRouiller
